deploy_path = /Users/volume999/Library/Application\ Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.92D18E48-93C3-43A5-81DA-18FF4777E65C

all: deploy

deploy:
	cp main.py $(deploy_path)